// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE61yHrxpV3bW9R8PysGxAbDwHfudUZbU',
    appId: '1:817226306814:web:abeba7042617660bec81af',
    messagingSenderId: '817226306814',
    projectId: 'fir-flutter-ffaaf',
    authDomain: 'fir-flutter-ffaaf.firebaseapp.com',
    storageBucket: 'fir-flutter-ffaaf.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJWCTMpogtm2B6gSo8yzjQZeX6oa_Icvg',
    appId: '1:817226306814:ios:b89a923a1db891a5ec81af',
    messagingSenderId: '817226306814',
    projectId: 'fir-flutter-ffaaf',
    storageBucket: 'fir-flutter-ffaaf.firebasestorage.app',
    iosBundleId: 'com.example.textapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE61yHrxpV3bW9R8PysGxAbDwHfudUZbU',
    appId: '1:817226306814:web:3824362b9cd9161fec81af',
    messagingSenderId: '817226306814',
    projectId: 'fir-flutter-ffaaf',
    authDomain: 'fir-flutter-ffaaf.firebaseapp.com',
    storageBucket: 'fir-flutter-ffaaf.firebasestorage.app',
  );

  // Configuración para Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key',
    appId: 'your-android-app-id',
    messagingSenderId: 'your-android-messaging-sender-id',
    projectId: 'fir-flutter-ffaaf',
    storageBucket: 'fir-flutter-ffaaf.firebasestorage.app',
    androidClientId: 'your-android-client-id',
  );

  // Configuración para iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-ios-messaging-sender-id',
    projectId: 'fir-flutter-ffaaf',
    storageBucket: 'fir-flutter-ffaaf.firebasestorage.app',
    iosBundleId: 'com.example.textapp',
  );
}